/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decks/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["get_deck_api_v1_decks__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Command */
        post: operations["post_command_api_v1_decks__token__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/export-blockers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export Blockers */
        get: operations["get_export_blockers_api_v1_decks__token__export_blockers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Focus
         * @description Where a tab is looking: its slide's clips generate first.
         */
        post: operations["post_focus_api_v1_decks__token__focus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation */
        get: operations["get_generation_api_v1_decks__token__generation_get"];
        put?: never;
        /**
         * Post Generation
         * @description Queue clips for generation (dedup'd across tabs; nearest-first).
         */
        post: operations["post_generation_api_v1_decks__token__generation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/generation/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Generation
         * @description Drop queued clips: this tab's (``owner``), or everything (the progress bar's ✕).
         */
        post: operations["cancel_generation_api_v1_decks__token__generation_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Job */
        post: operations["post_job_api_v1_decks__token__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pages */
        get: operations["get_pages_api_v1_decks__token__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description Review state for the deck (comparing pages can take a moment on a big deck).
         */
        get: operations["get_review_api_v1_decks__token__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/review/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Review Command */
        post: operations["post_review_command_api_v1_decks__token__review_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/slides/{slide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Slide */
        patch: operations["patch_slide_api_v1_decks__token__slides__slide_id__patch"];
        trace?: never;
    };
    "/api/v1/decks/{token}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck Stats */
        get: operations["get_deck_stats_api_v1_decks__token__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{engine}/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Engine Voices
         * @description An engine's pickable voices and its default (empty list = free-text ids).
         */
        get: operations["get_engine_voices_api_v1_engines__engine__voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Deck/job/source events. Hints to refetch; ``resync`` means refetch everything.
         */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppendOrphan */
        AppendOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /** Target Id */
            target_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "append_orphan";
        };
        /** AttachOrphan */
        AttachOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /** Target Id */
            target_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "attach_orphan";
        };
        /** AudioStatusDTO */
        AudioStatusDTO: {
            /** Cached */
            cached: number;
            /** Speech */
            speech: number;
        };
        /** BlockDTO */
        BlockDTO: {
            /** Segments */
            segments: (components["schemas"]["SpeechDTO"] | components["schemas"]["PauseDTO"])[];
            /** Slide Id */
            slide_id: string;
            transition_in: components["schemas"]["TransitionDTO"];
            transition_out: components["schemas"]["TransitionDTO"];
        };
        /** CancelGenerationRequest */
        CancelGenerationRequest: {
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /** Owner */
            owner?: string | null;
        };
        /**
         * ClipDTO
         * @description One utterance's audio under the snapshot's engine.
         */
        ClipDTO: {
            /** Bytes */
            bytes?: number | null;
            /** Cached */
            cached: boolean;
            /** Seconds */
            seconds?: number | null;
        };
        /** ClipRef */
        ClipRef: {
            /** Slide Id */
            slide_id: string;
            /** Speech Index */
            speech_index: number;
        };
        /** ConversationDTO */
        ConversationDTO: {
            /** Id */
            id: string;
            /** Is Deck */
            is_deck: boolean;
            /** Messages */
            messages: components["schemas"]["MessageDTO"][];
            /** Origin */
            origin: string;
            /** Slides */
            slides: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /**
             * Turn
             * @enum {string}
             */
            turn: "author" | "agent";
        };
        /** CountDTO */
        CountDTO: {
            /** Count */
            count: number;
        };
        /** DeckSnapshot */
        DeckSnapshot: {
            /** Aspect */
            aspect: number;
            /**
             * Default Engine
             * @enum {string}
             */
            default_engine: "kokoro" | "qwen3" | "inworld";
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticDTO"][];
            /**
             * Engine
             * @enum {string}
             */
            engine: "kokoro" | "qwen3" | "inworld";
            /** Engine Warm */
            engine_warm: boolean;
            /** Engines */
            engines: components["schemas"]["EngineDTO"][];
            /** Label */
            label: string;
            /** Missing Audio */
            missing_audio: number;
            /** Name */
            name: string;
            /** Narration */
            narration: {
                [key: string]: components["schemas"]["BlockDTO"];
            };
            /** Neighbours */
            neighbours: {
                [key: string]: string | null;
            };
            /** Orphans */
            orphans: string[];
            /** Pages */
            pages: components["schemas"]["PageDTO"][];
            /** Pdf Name */
            pdf_name: string;
            /** Review Active */
            review_active: boolean;
            revisions: components["schemas"]["RevisionsDTO"];
            /** Sidecar Name */
            sidecar_name: string;
            silence: components["schemas"]["SilenceDefaultsDTO"];
            /** Token */
            token: string;
            voices: components["schemas"]["VoicesDTO"];
        };
        /** DeckStatsDTO */
        DeckStatsDTO: {
            /** Errors */
            errors: number;
            /** Narrated */
            narrated: number;
            /** Slides */
            slides: number;
            /** Token */
            token: string;
            /** Warnings */
            warnings: number;
        };
        /** DeleteOrphan */
        DeleteOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delete_orphan";
        };
        /** DiagnosticDTO */
        DiagnosticDTO: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
            /** Slide Id */
            slide_id: string | null;
        };
        /** EditVoices */
        EditVoices: {
            /** Default Voice */
            default_voice?: string | null;
            /** Expected Revision */
            expected_revision: string;
            /** Renames */
            renames?: {
                [key: string]: string;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "edit_voices";
            /** Voices */
            voices: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** EngineDTO */
        EngineDTO: {
            /** Installed */
            installed: boolean;
            /** Name */
            name: string;
            /** Paid */
            paid: boolean;
            /** Realtime */
            realtime: boolean;
        };
        /** EngineVoicesDTO */
        EngineVoicesDTO: {
            /** Default */
            default: string | null;
            /**
             * Engine
             * @enum {string}
             */
            engine: "kokoro" | "qwen3" | "inworld";
            /** Voices */
            voices: string[];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExportJob */
        ExportJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "export";
        };
        /** FocusRequest */
        FocusRequest: {
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /** Slide Id */
            slide_id: string | null;
        };
        /** GenerateJob */
        GenerateJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "generate";
            /** Targets */
            targets?: components["schemas"]["ClipRef"][] | null;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Owner */
            owner?: string | null;
            /** Targets */
            targets?: components["schemas"]["ClipRef"][] | null;
        };
        /** GenerationRunningDTO */
        GenerationRunningDTO: {
            /** Elapsed */
            elapsed: number;
            /** Estimate */
            estimate: number | null;
            /** Slide Id */
            slide_id: string;
            /** Speech Index */
            speech_index: number;
        };
        /** GenerationStatusDTO */
        GenerationStatusDTO: {
            /** Done */
            done: number;
            /**
             * Engine
             * @enum {string}
             */
            engine: "kokoro" | "qwen3" | "inworld";
            /** Inflight */
            inflight: components["schemas"]["ClipRef"][];
            /** Last Error */
            last_error: string | null;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            running: components["schemas"]["GenerationRunningDTO"] | null;
            /** Total */
            total: number;
        };
        /** JobDTO */
        JobDTO: {
            /** Created At */
            created_at: number;
            /** Deck */
            deck: string;
            error: components["schemas"]["ErrorBody"] | null;
            /** Finished At */
            finished_at: number | null;
            /** Id */
            id: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "generate" | "preview" | "export" | "render_pages" | "warm";
            progress: components["schemas"]["ProgressDTO"];
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
        };
        /** LibraryDTO */
        LibraryDTO: {
            /** Root */
            root: string;
            /** Sections */
            sections: components["schemas"]["LibrarySectionDTO"][];
            /** Truncated */
            truncated: boolean;
            /** Unnarrated */
            unnarrated: components["schemas"]["LibraryDeckDTO"][];
        };
        /** LibraryDeckDTO */
        LibraryDeckDTO: {
            /** Group */
            group: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Narrated */
            narrated: boolean;
            /** Section */
            section: string;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /** LibrarySectionDTO */
        LibrarySectionDTO: {
            /** Decks */
            decks: components["schemas"]["LibraryDeckDTO"][];
            /** Title */
            title: string;
        };
        /** MessageDTO */
        MessageDTO: {
            /** At */
            at: string;
            /**
             * Author
             * @enum {string}
             */
            author: "author" | "agent" | "system";
            /** Text */
            text: string;
        };
        /**
         * MetaDTO
         * @description Static facts the editor needs: the transition gallery and the engines.
         */
        MetaDTO: {
            /** Aliases */
            aliases: {
                [key: string]: string;
            };
            /** Engines */
            engines: components["schemas"]["EngineDTO"][];
            /** Speeds */
            speeds: number[];
            /** Transitions */
            transitions: components["schemas"]["TransitionFamilyDTO"][];
        };
        /** PageDTO */
        PageDTO: {
            audio: components["schemas"]["AudioStatusDTO"];
            /** Clips */
            clips: components["schemas"]["ClipDTO"][];
            /** Image Url */
            image_url: string | null;
            incoming: components["schemas"]["TransitionDTO"];
            /** Index */
            index: number;
            /** Slide Id */
            slide_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "error" | "warning" | "ready" | "empty";
        };
        /**
         * PagesDTO
         * @description Page images only — cheap to refetch while pages render in the background.
         */
        PagesDTO: {
            /** Images */
            images: (string | null)[];
            /** Rendered */
            rendered: number;
        };
        /** PauseDTO */
        PauseDTO: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pause";
            /** Seconds */
            seconds: number;
        };
        /** PreviewJob */
        PreviewJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "preview";
            /**
             * Single Slide Transitions
             * @default false
             */
            single_slide_transitions: boolean;
            /** Slide Id */
            slide_id?: string | null;
            /** Start Slide */
            start_slide?: string | null;
        };
        /** ProgressDTO */
        ProgressDTO: {
            /** Done */
            done: number;
            /** Label */
            label: string;
            /** Phase */
            phase: string;
            /** Total */
            total: number;
        };
        /** RenderPagesJob */
        RenderPagesJob: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "render_pages";
            /**
             * Near
             * @default 0
             */
            near: number;
        };
        /** ReviewAccept */
        ReviewAccept: {
            /** Conversation */
            conversation: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "accept";
        };
        /** ReviewClear */
        ReviewClear: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "clear";
        };
        /** ReviewComment */
        ReviewComment: {
            /** Slides */
            slides: string[];
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "comment";
        };
        /**
         * ReviewDTO
         * @description Review for one deck. ``active`` false: no base could be taken (a final build).
         */
        ReviewDTO: {
            /** Active */
            active: boolean;
            /** Badges */
            badges: {
                [key: string]: string;
            };
            /** Base Images */
            base_images: {
                [key: string]: string;
            };
            /** Base Order */
            base_order: string[];
            /** Changes */
            changes: components["schemas"]["SlideChangeDTO"][];
            /** Conversations */
            conversations: components["schemas"]["ConversationDTO"][];
            /** Diffs */
            diffs: {
                [key: string]: string[][];
            };
            /** Final Build */
            final_build: boolean;
            /** Pending */
            pending: {
                [key: string]: string[];
            };
            /** Unfiled */
            unfiled: string[];
        };
        /** ReviewFileUnrequested */
        ReviewFileUnrequested: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file_unrequested";
        };
        /**
         * ReviewMarkSeen
         * @description Everything as it is now becomes the base: no changes left to look at.
         */
        ReviewMarkSeen: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mark_seen";
        };
        /** ReviewOutcomeDTO */
        ReviewOutcomeDTO: {
            /** Conversation */
            conversation: string | null;
            /** Count */
            count: number;
            /** Focus */
            focus: boolean;
            /** Message */
            message: string;
        };
        /** ReviewReopen */
        ReviewReopen: {
            /** Conversation */
            conversation: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reopen";
        };
        /** ReviewReply */
        ReviewReply: {
            /** Conversation */
            conversation: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reply";
        };
        /** RevisionsDTO */
        RevisionsDTO: {
            /** Config */
            config: string;
            /** Narration */
            narration: string;
            /** Pdf */
            pdf: string;
            /** Review */
            review: string;
        };
        /** SaveResponse */
        SaveResponse: {
            /** Changed */
            changed: boolean;
            /** Revision */
            revision: string;
        };
        /** SessionDTO */
        SessionDTO: {
            /** Token */
            token: string;
        };
        /**
         * SilenceDefaultsDTO
         * @description The deck's hold before and after a slide's speech when none is written.
         */
        SilenceDefaultsDTO: {
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /** SlideChangeDTO */
        SlideChangeDTO: {
            /** Base Index */
            base_index: number | null;
            /** Current Index */
            current_index: number | null;
            /** Image */
            image: boolean;
            /** Kinds */
            kinds: string[];
            /** Moved */
            moved: boolean;
            /** Narration */
            narration: boolean;
            /** Slide Id */
            slide_id: string;
        };
        /** SlideEdit */
        SlideEdit: {
            /** Expected Revision */
            expected_revision: string;
            /** Segments */
            segments: (components["schemas"]["SpeechDTO"] | components["schemas"]["PauseDTO"])[];
            transition_in?: components["schemas"]["TransitionDTO"];
            transition_out?: components["schemas"]["TransitionDTO"];
        };
        /** SpeechDTO */
        SpeechDTO: {
            /** Direction */
            direction?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "speech";
            /** Pace */
            pace?: ("slow" | "normal" | "fast") | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Voice */
            voice?: string | null;
        };
        /** TransitionDTO */
        TransitionDTO: {
            /**
             * Kind
             * @default cut
             */
            kind: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
        };
        /** TransitionFamilyDTO */
        TransitionFamilyDTO: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Options */
            options: [
                string,
                string
            ][];
        };
        /** VoicesDTO */
        VoicesDTO: {
            /** Default Voice */
            default_voice: string | null;
            /** Map */
            map: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Names */
            names: string[];
            /** Resolved */
            resolved: {
                [key: string]: string | null;
            };
        };
        /** WarmJob */
        WarmJob: {
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "warm";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_deck_api_v1_decks__token__get: {
        parameters: {
            query?: {
                engine?: ("kokoro" | "qwen3" | "inworld") | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSnapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_command_api_v1_decks__token__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachOrphan"] | components["schemas"]["AppendOrphan"] | components["schemas"]["DeleteOrphan"] | components["schemas"]["EditVoices"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_export_blockers_api_v1_decks__token__export_blockers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_focus_api_v1_decks__token__focus_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FocusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_generation_api_v1_decks__token__generation_get: {
        parameters: {
            query?: {
                engine?: ("kokoro" | "qwen3" | "inworld") | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStatusDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_generation_api_v1_decks__token__generation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStatusDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_generation_api_v1_decks__token__generation_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_job_api_v1_decks__token__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateJob"] | components["schemas"]["PreviewJob"] | components["schemas"]["ExportJob"] | components["schemas"]["RenderPagesJob"] | components["schemas"]["WarmJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pages_api_v1_decks__token__pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagesDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_review_api_v1_decks__token__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_review_command_api_v1_decks__token__review_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewMarkSeen"] | components["schemas"]["ReviewComment"] | components["schemas"]["ReviewReply"] | components["schemas"]["ReviewAccept"] | components["schemas"]["ReviewReopen"] | components["schemas"]["ReviewClear"] | components["schemas"]["ReviewFileUnrequested"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOutcomeDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_slide_api_v1_decks__token__slides__slide_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlideEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_deck_stats_api_v1_decks__token__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckStatsDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_engine_voices_api_v1_engines__engine__voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engine: "kokoro" | "qwen3" | "inworld";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineVoicesDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                deck?: string | null;
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_library_api_v1_library_get: {
        parameters: {
            query?: {
                rescan?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
