/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decks/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["get_deck_api_v1_decks__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Command */
        post: operations["post_command_api_v1_decks__token__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/export-blockers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export Blockers */
        get: operations["get_export_blockers_api_v1_decks__token__export_blockers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Job */
        post: operations["post_job_api_v1_decks__token__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decks/{token}/slides/{slide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Slide */
        patch: operations["patch_slide_api_v1_decks__token__slides__slide_id__patch"];
        trace?: never;
    };
    "/api/v1/decks/{token}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck Stats */
        get: operations["get_deck_stats_api_v1_decks__token__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Deck/job/source events. Hints to refetch; ``resync`` means refetch everything.
         */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppendOrphan */
        AppendOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /** Target Id */
            target_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "append_orphan";
        };
        /** AttachOrphan */
        AttachOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /** Target Id */
            target_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "attach_orphan";
        };
        /** AudioStatusDTO */
        AudioStatusDTO: {
            /** Cached */
            cached: number;
            /** Speech */
            speech: number;
        };
        /** BlockDTO */
        BlockDTO: {
            /** Segments */
            segments: (components["schemas"]["SpeechDTO"] | components["schemas"]["PauseDTO"])[];
            /** Slide Id */
            slide_id: string;
            transition_in: components["schemas"]["TransitionDTO"];
            transition_out: components["schemas"]["TransitionDTO"];
        };
        /** ClipRef */
        ClipRef: {
            /** Slide Id */
            slide_id: string;
            /** Speech Index */
            speech_index: number;
        };
        /** DeckSnapshot */
        DeckSnapshot: {
            /**
             * Default Engine
             * @enum {string}
             */
            default_engine: "kokoro" | "qwen3" | "inworld";
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticDTO"][];
            /**
             * Engine
             * @enum {string}
             */
            engine: "kokoro" | "qwen3" | "inworld";
            /** Engines */
            engines: components["schemas"]["EngineDTO"][];
            /** Label */
            label: string;
            /** Missing Audio */
            missing_audio: number;
            /** Name */
            name: string;
            /** Narration */
            narration: {
                [key: string]: components["schemas"]["BlockDTO"];
            };
            /** Orphans */
            orphans: string[];
            /** Pages */
            pages: components["schemas"]["PageDTO"][];
            /** Pdf Name */
            pdf_name: string;
            /** Review Active */
            review_active: boolean;
            revisions: components["schemas"]["RevisionsDTO"];
            /** Sidecar Name */
            sidecar_name: string;
            /** Token */
            token: string;
            voices: components["schemas"]["VoicesDTO"];
        };
        /** DeckStatsDTO */
        DeckStatsDTO: {
            /** Errors */
            errors: number;
            /** Narrated */
            narrated: number;
            /** Slides */
            slides: number;
            /** Token */
            token: string;
            /** Warnings */
            warnings: number;
        };
        /** DeleteOrphan */
        DeleteOrphan: {
            /** Expected Revision */
            expected_revision: string;
            /** Orphan Id */
            orphan_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delete_orphan";
        };
        /** DiagnosticDTO */
        DiagnosticDTO: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
            /** Slide Id */
            slide_id: string | null;
        };
        /** EditVoices */
        EditVoices: {
            /** Default Voice */
            default_voice?: string | null;
            /** Expected Revision */
            expected_revision: string;
            /** Renames */
            renames?: {
                [key: string]: string;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "edit_voices";
            /** Voices */
            voices: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** EngineDTO */
        EngineDTO: {
            /** Installed */
            installed: boolean;
            /** Name */
            name: string;
            /** Paid */
            paid: boolean;
            /** Realtime */
            realtime: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExportJob */
        ExportJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "export";
        };
        /** GenerateJob */
        GenerateJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "generate";
            /** Targets */
            targets?: components["schemas"]["ClipRef"][] | null;
        };
        /** JobDTO */
        JobDTO: {
            /** Created At */
            created_at: number;
            /** Deck */
            deck: string;
            error: components["schemas"]["ErrorBody"] | null;
            /** Finished At */
            finished_at: number | null;
            /** Id */
            id: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "generate" | "preview" | "export" | "render_pages";
            progress: components["schemas"]["ProgressDTO"];
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
        };
        /** LibraryDTO */
        LibraryDTO: {
            /** Root */
            root: string;
            /** Sections */
            sections: components["schemas"]["LibrarySectionDTO"][];
            /** Truncated */
            truncated: boolean;
            /** Unnarrated */
            unnarrated: components["schemas"]["LibraryDeckDTO"][];
        };
        /** LibraryDeckDTO */
        LibraryDeckDTO: {
            /** Group */
            group: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Narrated */
            narrated: boolean;
            /** Section */
            section: string;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /** LibrarySectionDTO */
        LibrarySectionDTO: {
            /** Decks */
            decks: components["schemas"]["LibraryDeckDTO"][];
            /** Title */
            title: string;
        };
        /** PageDTO */
        PageDTO: {
            audio: components["schemas"]["AudioStatusDTO"];
            /** Image Url */
            image_url: string | null;
            incoming: components["schemas"]["TransitionDTO"];
            /** Index */
            index: number;
            /** Slide Id */
            slide_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "error" | "warning" | "ready" | "empty";
        };
        /** PauseDTO */
        PauseDTO: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pause";
            /** Seconds */
            seconds: number;
        };
        /** PreviewJob */
        PreviewJob: {
            /**
             * Allow Paid
             * @default false
             */
            allow_paid: boolean;
            /** Engine */
            engine?: ("kokoro" | "qwen3" | "inworld") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "preview";
            /**
             * Single Slide Transitions
             * @default false
             */
            single_slide_transitions: boolean;
            /** Slide Id */
            slide_id?: string | null;
            /** Start Slide */
            start_slide?: string | null;
        };
        /** ProgressDTO */
        ProgressDTO: {
            /** Done */
            done: number;
            /** Label */
            label: string;
            /** Phase */
            phase: string;
            /** Total */
            total: number;
        };
        /** RenderPagesJob */
        RenderPagesJob: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "render_pages";
        };
        /** RevisionsDTO */
        RevisionsDTO: {
            /** Config */
            config: string;
            /** Narration */
            narration: string;
            /** Pdf */
            pdf: string;
            /** Review */
            review: string;
        };
        /** SaveResponse */
        SaveResponse: {
            /** Changed */
            changed: boolean;
            /** Revision */
            revision: string;
        };
        /** SessionDTO */
        SessionDTO: {
            /** Token */
            token: string;
        };
        /** SlideEdit */
        SlideEdit: {
            /** Expected Revision */
            expected_revision: string;
            /** Segments */
            segments: (components["schemas"]["SpeechDTO"] | components["schemas"]["PauseDTO"])[];
            transition_in?: components["schemas"]["TransitionDTO"];
            transition_out?: components["schemas"]["TransitionDTO"];
        };
        /** SpeechDTO */
        SpeechDTO: {
            /** Direction */
            direction?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "speech";
            /** Pace */
            pace?: ("slow" | "normal" | "fast") | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Voice */
            voice?: string | null;
        };
        /** TransitionDTO */
        TransitionDTO: {
            /**
             * Kind
             * @default cut
             */
            kind: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
        };
        /** VoicesDTO */
        VoicesDTO: {
            /** Default Voice */
            default_voice: string | null;
            /** Map */
            map: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Names */
            names: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_deck_api_v1_decks__token__get: {
        parameters: {
            query?: {
                engine?: ("kokoro" | "qwen3" | "inworld") | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSnapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_command_api_v1_decks__token__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachOrphan"] | components["schemas"]["AppendOrphan"] | components["schemas"]["DeleteOrphan"] | components["schemas"]["EditVoices"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_export_blockers_api_v1_decks__token__export_blockers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_job_api_v1_decks__token__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateJob"] | components["schemas"]["PreviewJob"] | components["schemas"]["ExportJob"] | components["schemas"]["RenderPagesJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_slide_api_v1_decks__token__slides__slide_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlideEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_deck_stats_api_v1_decks__token__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckStatsDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                deck?: string | null;
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_library_api_v1_library_get: {
        parameters: {
            query?: {
                rescan?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
